#!/bin/sh

if [ "$1" = "config" ]; then

echo 'graph_title IPtables drop packets'
echo 'graph_vlabel packets per second'
echo 'graph_category network'
echo 'graph_args --base 1000 -l 0'

# DROPPED_IN
echo 'in.label IN'
echo 'in.type DERIVE'
if [ -n "$in_warning" ]; then
 echo "in.warning $in_warning"
else
 echo "in.warning 2"
fi

# DROPPED INVALID IN
echo 'in_invalid.label IN-INVALID'
echo 'in_invalid.type DERIVE'
if [ -n "$in_invalid_warning" ]; then
 echo "in_invalid.warning $in_invalid_warning"
else
echo "in_invalid.warning 2"
fi

# DROPPED OUT
echo 'out.label OUT'
echo 'out.type DERIVE'
if [ -n "$out_warning" ]; then
 echo "out.warning $out_warning"
else
 echo "out.warning 2"
fi

# DROPPED ApACHE IN
echo 'apache.label APACHE'
echo 'apache.type DERIVE'
if [ -n "$apache_warning" ]; then
 echo "apache.warning $apache_warning"
else
 echo "apache.warning 2"
fi

fi

iptables -L -vn -x | grep -w "DROPPED_IN" | awk '{print "in.value " $1; exit 0;}'
iptables -L -vn -x | grep -w "DROPPED_APACHE" | awk '{print "apache.value " $1; exit 0;}'
iptables -L -vn -x | grep -w "DROPPED_OUT" | awk '{print "out.value " $1; exit 0;}'
iptables -L -vn -x | grep -w "DROPPED_INVALID_IN" | awk '{print "in_invalid.value " $1; exit 0;}'
